#FROM maven:3-jdk-8-alpine
FROM maven:3.5-jdk-8

# 维护者信息
MAINTAINER deltaqin "delta_qin@163.com"

# 声明作用
EXPOSE 8080

#WORKDIR /app

# 直接使用服务器maven编译，不在本地编译，太低效
#ADD target/ssm.jar /app/target/ssm.jar


#ADD run.sh /app
#
## ENTRYPOINT设定了启动镜像时要启动的命令(./run.sh)
#ENTRYPOINT ./run.sh
